version: '3.7'
services:

  client:
    container_name: cliente-http
    build: ./Client
    depends_on:
      - redis
      - redis2
      - redis3
      # - redis
    ports:
      - "3000:3000"
      
  grpc_server:
    container_name: servidor-grpc
    build: ./ServerJS
    depends_on:
      - postgres
    ports:
      - "8030:8030"

  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - ./Database/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=tiendita
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: bitnami/redis:6.0
    container_name: redis-tarea1-1
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    
  redis2:
    image: bitnami/redis:6.0
    container_name: redis-tarea1-2
    ports:
      - "7001:6379"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_PORT_NUMBER=6379
    restart: always
    
  redis3:
    image: bitnami/redis:6.0
    container_name: redis-tarea1-3
    ports:
      - "7002:6379"
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
