version: '3.7'
services:

  client:
    container_name: Cliente
    build: ./Client
    depends_on:
      - redis
      - redis2
      - redis3
    ports:
      - "3000:3000"
      
  grpc_server:
    container_name: Server
    build: ./ServerJS
    depends_on:
      - postgres
    ports:
      - "8030:8030"

  postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
      - ./Database/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_DATABASE=xoogle
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    container_name: cache
    image: redis:6.2.6
    restart: always
    ports:
      - "8031:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis",
        "--maxmemory 2mb",
        "--maxmemory-policy allkeys-lfu"
      ]
  redis2:
    container_name: cache2
    image: redis:6.2.6
    restart: always
    ports:
      - "8032:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis2",
        "--maxmemory 1mb",
        "--maxmemory-policy allkeys-random"
      ]
  
  redis3:
    container_name: cache3
    image: redis:6.2.6
    restart: always
    ports:
      - "8033:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command:
      [
        "redis-server",
        "--bind",
        "redis3",
        "--maxmemory 1mb",
        "--maxmemory-policy allkeys-lru"
      ]